spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8881/
          predicates:
            - Path=/customers/**
        - id: r2
          uri: http://localhost:8882/
          predicates:
            - Path=/accounts/**
  application:
    name: gateway
server:
   port: 8888